# REPLACE any existing mappings with these

################################################################################
# A single, top-level setting is defined: "@frameworks". This setting can
# be included and referenced wherever shared frameworks are required.

frameworks:
  # qtwidgets - collection of Toolkit related QT Widgets
  # tk-framework-qtwidgets_v2.x.x:
  #   location:
  #     type: git
  #     path: git@github.com:wwfxuk/tk-framework-qtwidgets.git
  #     version: v2.8.3+wwfx.1.1.0
    tk-framework-qtwidgets_v2.x.x:
      location:
        version: v2.10.3
        type: app_store
        name: tk-framework-qtwidgets

  # shotgunutils v5 - Shotgun Related Utilities
  # tk-framework-shotgunutils_v5.x.x:
  #     location:
  #         version: v5.6.1
  #         type: app_store
  #         name: tk-framework-shotgunutils

  tk-framework-shotgunutils_v5.x.x:
    location:
      version: v5.8.5
      type: app_store
      name: tk-framework-shotgunutils
