# Append these Katana settings to existing lists/mappings

keys:
    katana.output:
        alias: output
        type: str
        filter_by: '[A-Za-z_0-9]+?'


paths:
    #
    # Katana
    #

    ##
    ## Shot
    ##

    shot_work_area_katana:
        definition: '@shot_work_area/katana'
    katana_shot_work:
        definition: '@shot_work_area/katana/scenes/{Shot}_{Step}[_{name}]_{User}_v{version}.katana'
    katana_shot_snapshot:
        definition: '@shot_work_area/katana/snapshots/{Shot}_{Step}[_{name}]_{User}_v{version}.{timestamp}.katana'
    shot_publish_area_katana:
        definition: '@shot_publish_area/katana'
    katana_shot_publish:
        definition: '@shot_publish_area/katana/scenes/{Shot}_{Step}[_{name}]_v{version}.katana'
    katana_shot_look_file:
        definition: '@shot_work_area/katana/scenes/klf/{name}/v{version}/{Shot}_{Step}_{name}_v{version}.klf'
    katana_shot_publish_look_file:
        definition: '@shot_publish_area/katana/scenes/klf/{name}/v{version}/{Shot}_{Step}_{name}_v{version}.klf'

    # Rendered images
    katana_shot_render:
        definition: '@shot_work_area/katana/render/{name}/v{version}/{katana.output}/{Shot}_{katana.output}_v{version}.{SEQ}.exr'
    katana_shot_publish_render:
        definition: '@shot_publish_area/katana/render/{name}/v{version}/{katana.output}/{Shot}_{katana.output}_v{version}.{SEQ}.exr'

    ##
    ## Asset
    ##

    asset_work_area_katana:
        definition: '@asset_work_area/katana'
    katana_asset_work:
        definition: '@asset_work_area/katana/scenes/{Asset}_{Step}[_{name}]_{User}_v{version}.katana'
    katana_asset_snapshot:
        definition: '@asset_work_area/katana/snapshots/{Asset}_{Step}[_{name}]_{User}_v{version}.{timestamp}.katana'
    asset_publish_area_katana:
        definition: '@asset_publish_area/katana'
    katana_asset_publish:
        definition: '@asset_publish_area/katana/scenes/{Asset}_{Step}[_{name}]_v{version}.katana'
    katana_asset_look_file:
        definition: '@asset_work_area/katana/scenes/klf/{name}/v{version}/{Asset}_{Step}_{name}_v{version}.klf'
    katana_asset_publish_look_file:
        definition: '@asset_publish_area/katana/scenes/klf/{name}/v{version}/{Asset}_{Step}_{name}_v{version}.klf'


    # Rendered images
    katana_asset_render:
        definition: '@asset_work_area/katana/render/v{version}/{name}/{Asset}_{name}_v{version}.{SEQ}.exr'
    katana_asset_publish_render:
        definition: '@asset_publish_area/katana/render/v{version}/{name}/{Asset}_{name}_v{version}.{SEQ}.exr'
