# Add this Katana settings section to somewhere in the file

################################################################################

# ---- Katana

# Generic, basic Katana config so at least we can "File Open..." correctly
settings.tk-multi-workfiles2.katana:
  hook_scene_operation: "{engine}/tk-multi-workfiles2/scene_operation_tk-katana.py"
  location: "@apps.tk-multi-workfiles2.location"

# asset_step
settings.tk-multi-workfiles2.katana.asset_step:
  hook_scene_operation: "{engine}/tk-multi-workfiles2/scene_operation_tk-katana.py"
  template_publish: katana_asset_publish
  template_publish_area: asset_publish_area_katana
  template_work: katana_asset_work
  template_work_area: asset_work_area_katana
  location: "@apps.tk-multi-workfiles2.location"

# shot_step
settings.tk-multi-workfiles2.katana.shot_step:
  hook_scene_operation: "{engine}/tk-multi-workfiles2/scene_operation_tk-katana.py"
  template_publish: katana_shot_publish
  template_publish_area: shot_publish_area_katana
  template_work: katana_shot_work
  template_work_area: shot_work_area_katana
  location: '@apps.tk-multi-workfiles2.location'
